### ISSUE TITLE
Can't close GPPNativeShareBuilder

### ISSUE THREAD

**Issue by IhorShevchuk** [lysannschlegel/GooglePlusShareActivity#10]
I got next error when using this dialog: I can't close this dialog. 
Please follow next steps:
1. Open this dialog.
2. Tap 'Cancel' on left up corner.
3. Tap 'No' on ActionShit
4. Next tries to close this dialog will not be succeed :-(

**Comment by lysannschlegel** [comment]
This is a duplicate of #8. Please see my comment there, and be sure to vote for the issue on Google code.
